### ISSUE TITLE
Cannot add commands, no response!

### ISSUE THREAD

**Issue by bbgun2821** [serversigns/ServerSigns#21]
When I execute a /svs add command, it tells me to right click the sign.  I do this and get no response, in fact, when I try to place another sign or item it immediately deletes that item I placed.  The only way to cancel this is /svs void, to which is responds with "success" and returns to normal.  I can't find anything online to assist with why this may be happening!

**Comment by bbgun2821** [comment]
UPDATE:  It works on signs that are placed on the ground however does not work with signs that are placed on the wall.  This is what I am trying to achieve, unfortunately, to command log a sign placed on the wall.

**Comment by EpiCanard** [comment]
Which version of Minecraft do you use ?
Which version of ServerSigns do you use ?
Did you migrate recently your server to a newer version of Minecraft and didn't reset the config file of ServerSigns ?

**Comment by bbgun2821** [comment]
I use 1.15 of Spigot. I’ve installed the server signs plugin after the change, so I’m actually unsure.

**Comment by c0wg0d** [comment]
I am having the exact same issue.  I posted the following on spigotmc already but I'll copy/paste here too.

I am getting the following error. I've tried official 4.6.0 as well as the latest dev build #32, same error. It happens when right clicking a sign after issuing /svs add say hi

Running paper 1.15.2 build 137.

I will note that v4.5.3 works for an oak sign that is free standing, and does not work for an oak sign on the wall, but in v4.6.0, both types of signs give the following error. And yes I have regenerated my config to allow for all the new sign types:

blocks:
- ACACIA_SIGN
- ACACIA_WALL_SIGN
- BIRCH_SIGN
- BIRCH_WALL_SIGN
- DARK_OAK_SIGN
- DARK_OAK_WALL_SIGN
- JUNGLE_SIGN
- JUNGLE_WALL_SIGN
- OAK_SIGN
- OAK_WALL_SIGN
- SPRUCE_SIGN
- SPRUCE_WALL_SIGN

[23:33:10 ERROR]: Could not pass event PlayerInteractEvent to ServerSigns v4.6.0
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getRelative(CraftBlock.java:247) ~[patched_1.15.2.jar:git-Paper-121]
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getRelative(CraftBlock.java:242) ~[patched_1.15.2.jar:git-Paper-121]
at de.czymm.serversigns.signs.ServerSign.updateProtectedBlocks(ServerSign.java:516) ~[?:?]
at de.czymm.serversigns.signs.ServerSign.setLocation(ServerSign.java:137) ~[?:?]
at de.czymm.serversigns.signs.ServerSign.<init>(ServerSign.java:124) ~[?:?]
at de.czymm.serversigns.listeners.AdminListener.handleAdminInteract(AdminListener.java:120) ~[?:?]
at de.czymm.serversigns.listeners.AdminListener.adminInteractCheck(AdminListener.java:103) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor528.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-121]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-121]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-121]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-121]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1374) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-121]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-121]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by EpiCanard** [comment]
I'm not sure but I think it is the same error of #10

Thanks to both of you for your help and your details I will investigate to find the problem.

**Comment by EpiCanard** [comment]
To which kind of block is attached your wall sign ?

**Comment by EpiCanard** [comment]
It seems to be an issue only with paper spigot
And it append only with oak signs, I can assign command to spruce sign

**Comment by c0wg0d** [comment]
Very weird.  I hope it can be fixed to work with Paper Spigot.  I will try other sign types to see if they work as you described.

And to answer your question, I was attaching the oak sign to a concrete block.

**Comment by bbgun2821** [comment]
I’m not entirely sure whether I’m using paper spigot or not.  I tried on a Stone block.  Additionally I tried on multiple blocks for trial and error, Wood block, bricks, iron block, cannot find a block that works outside of a free standing sign!

Also, hey C0wg0d!  Fancy meeting you here!  Don’t hate me but I’m literally trying to set up the gold to cash system that sandlot has for my local dedicated server with friends.  Hope all is well!

BB

**Comment by EpiCanard** [comment]
The error come from protection of blocks. In newest version of minecraft block attached to sign is not protected anymore.

When it try to get the sign block it say it is AIR for bukkit but for paper spigot it say it is LEGACY_WALL_SIGN with no data when it is oak sign or AIR for other block. So it can't protect sign.

**Comment by c0wg0d** [comment]
Can we add "LEGACY_WALL_SIGN" to our list of blocks in the config to work around the issue?

**Comment by EpiCanard** [comment]
no, these materials exist to keep a compatibility with old versions and should not be used with new versions

**Comment by c0wg0d** [comment]
Okay, so does this mean it's impossible to use oak signs on walls when using Paper Spigot in legacy mode?  It seems like legacy mode is still required for a large number of popular plugins, including Dynmap, HubKick, and BanManager.

**Comment by EpiCanard** [comment]
I think the way to get an attached block has changed with newest version and the actual way used is wrong

**Comment by EpiCanard** [comment]
I confirm it is the way to get attached block. I will fix that tomorrow :)

**Comment by EpiCanard** [comment]
Fixed, now the best part, try every version to verify that nothing is broken

**Comment by c0wg0d** [comment]
I can help test if you release a new dev build.

**Comment by EpiCanard** [comment]
We have now a pipeline for every development builds made on develop. Yeah \o/
You can find the build here https://ci.serversigns.de/job/ServerSigns-dev-builds/2/
I also fixed the error with the command that was not executed on the whole door.
I only tested 1.15, 1.14 and 1.13 for now more tests coming :)

**Comment by EpiCanard** [comment]
Fixed and tested on every version of minecraft :)

**Comment by c0wg0d** [comment]
I tested the dev built you linked above on Paper 1.15.2 and it worked as expected.  Thank you!

**Comment by EpiCanard** [comment]
The version is released, I close this issue :)
https://dev.bukkit.org/projects/serversigns/files/2915106
