### ISSUE TITLE
ERROR when server start up.

### ISSUE THREAD

**Issue by flandretw** [serversigns/ServerSigns#33]
```
[09:21:54 ERROR]: [ServerSigns] The updater could not contact dev.bukkit.org for updating.
[09:21:54 ERROR]: [ServerSigns] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[09:21:54 ERROR]: [ServerSigns] null
java.io.IOException: Server returned HTTP response code: 503 for URL: https://api.curseforge.com/servermods/files?projectIds=33254
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_251]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_251]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_251]
        at de.czymm.serversigns.Updater.read(Updater.java:734) ~[?:?]
        at de.czymm.serversigns.Updater.runUpdater(Updater.java:809) ~[?:?]
        at de.czymm.serversigns.Updater.access$100(Updater.java:55) ~[?:?]
        at de.czymm.serversigns.Updater$UpdateRunnable.run(Updater.java:804) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by EpiCanard** [comment]
Hello,

Do you still have the error right now ?
Does your server have access to Internet ?
If the error persist you can set the config parameter `check_for_updates` to false.

The error come from the fact it can't auto update itself because the bukkit api return a 503 error.

**Comment by EpiCanard** [comment]
This is only a log error when the bukkit api is not available and not a crash of the plugin.

I close this issue, it's a normal behavior.
