### ISSUE TITLE
Colon inside json command string breaks ServerSigns.

### ISSUE THREAD

**Issue by mibby** [serversigns/ServerSigns#42]
ServerSigns v4.6.2

The command works in-game fine but when attached to ServerSigns, the plugin outputs an exception.

```
commands:
  '0':
    command: tellraw @p ["",{"text":"Correct Answer: ","color":"dark_green"},{"text":"Swearing is never allowed. ","color":"gold"}]
    type: SERVER_COMMAND
    delay: 0
    grantPerms: []
    alwaysPersisted: false
    interactValue: 0
```

```
[23:29:46] [Server thread/ERROR]: Cannot load plugins/ServerSigns/signs/spawn_1153_72_-265.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 19, column 52:
     ... w @p ["",{"text":"Correct Answer: ","color":"dark_green"},{"text ... 
                                         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at de.czymm.serversigns.signs.ServerSignManager.prepareServerSignsSet(ServerSignManager.java:95) ~[?:?]
	at de.czymm.serversigns.commands.SubCommandReload.execute(SubCommandReload.java:49) ~[?:?]
	at de.czymm.serversigns.commands.core.SubCommand.execute(SubCommand.java:57) ~[?:?]
	at de.czymm.serversigns.commands.CommandServerSigns.perform(CommandServerSigns.java:113) ~[?:?]
	at de.czymm.serversigns.commands.core.Command.run(Command.java:84) ~[?:?]
	at de.czymm.serversigns.ServerSignsPlugin.onCommand(ServerSignsPlugin.java:185) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2121) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1924) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1877) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1218) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1211) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1187) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1027) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 19, column 52:
     ... w @p ["",{"text":"Correct Answer: ","color":"dark_green"},{"text ... 
                                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:869) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[1.16.5-patched.jar:git-Yatopia-dev/cadmium-"ab4c007"]
	... 29 more
```

**Comment by EpiCanard** [comment]
Hello,

It is strange in the log error it tell there is a `:` after Answer.

Did you change something in the sign yml file ?
Can you send the content of `spawn_1153_72_-265.yml` ?

**Comment by mibby** [comment]
My apologies, I incorrectly copied the edited sign used to temp fix the issue. There _is_ a colon in the sign command after Answer. Having a colon in the json breaks ServerSigns but is functionally fine in vanilla.

**Comment by EpiCanard** [comment]
Yes, `:` must be escaped in yaml to prevent this issue.

**Comment by mibby** [comment]
Ah, I see. I'll give it a try.

I did however seem to come across another problem. PlaceholderAPI placeholders do not seem to work in command broadcast types.

It outputs ``%player_displayname%`` instead of the PAPI placeholder of the user who clicked. Testing with ``/papi parse <name> %player_displayname%``, the placeholder displays fine.

```
commands:
  '0':
    command: "%player_displayname% &dhas passed the introduction!"
    type: BROADCAST
    delay: 0
    grantPerms: []
    alwaysPersisted: false
    interactValue: 0
```

**Comment by EpiCanard** [comment]
The file you are displaying has been generated by SVS or you added yourself the line in the file ?

**Comment by mibby** [comment]
I've tried both ways. This is how SVS generated the command line when I typed ``/svs add <broadcast> %player_displayname% test``.

```
  '7':
    command: '%player_displayname% test'
    type: BROADCAST
    delay: 0
    grantPerms: []
    alwaysPersisted: false
    interactValue: 0
```

Edit: Confirmed escaping the character manually with | does work. So just PAPI placeholders not working.

```
  '0':
    command: |
      tellraw @p ["",{"text":"Correct Answer: ","color":"dark_green"},{"text":"Swearing is never allowed. ","color":"gold"}]
    type: SERVER_COMMAND
    delay: 0
    grantPerms: []
    alwaysPersisted: false
    interactValue: 0
```

**Comment by EpiCanard** [comment]
If /papi parse works everything should works as expected.
Do you have any error in the console ?
Witch version of ServerSigns and minecraft are you using ?

**Comment by mibby** [comment]
Minecraft 1.16.5
ServerSigns 4.6.2 (dev 34)
PlaceholderAPI 2.10.10 (dev 122)

No errors that I can see.

**Comment by EpiCanard** [comment]
Hum so not an old version

**Comment by mibby** [comment]
Yeah, I'm really not too sure why it doesn't work since parsing does. Unless ServerSigns isn't hooking into PAPI properly.

**Comment by EpiCanard** [comment]
Can you do a /svs dev hooks ?

**Comment by mibby** [comment]
```Vault: true, NCP: false, Ess: true, PAPI: true```

**Comment by EpiCanard** [comment]
So Papi is well hooked.

I'm at work currently, I will try on my side this evening (in 9h #France).

**Comment by EpiCanard** [comment]
I succeed to reproduce the bug, so it seems there is really a bug.

**Comment by EpiCanard** [comment]
Officially it's not a bug. It's just that all commands that doesn't need a player (\<server> and \<broadcast>) couldn't have access to placeholder. But it's fixed.
You can use the last dev build https://ci.serversigns.de/job/ServerSigns-dev-builds/15/

**Comment by mibby** [comment]
Confirmed working and fixed, thanks!
