### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by Dude42069Nice** [serversigns/ServerSigns#45]
I was using serversigns for about a week and everything was working as intendet but yesterday when i tried using /svs import command it didnt work.

[09:59:59 INFO]: Dude issued server command: /svs import wiadro.txt
[10:00:01 WARN]: [ServerSigns] An error occurred while importing file 'wiadro.txt'
java.io.FileNotFoundException: wiadro.txt (Nie można odnaleźć określonego pliku)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:211) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:153) ~[?:?]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:120) ~[patched_1.16.5.jar:git-Paper-445]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:110) ~[patched_1.16.5.jar:git-Paper-445]
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456) ~[patched_1.16.5.jar:git-Paper-445]
        at com.google.common.io.CharSource.readLines(CharSource.java:311) ~[patched_1.16.5.jar:git-Paper-445]
        at com.google.common.io.Files.readLines(Files.java:553) ~[patched_1.16.5.jar:git-Paper-445]
        at com.google.common.io.Files.readLines(Files.java:520) ~[patched_1.16.5.jar:git-Paper-445]
        at de.czymm.serversigns.listeners.AdminListener.handleAdminInteract(AdminListener.java:256) ~[?:?]
        at de.czymm.serversigns.listeners.AdminListener.adminInteractCheck(AdminListener.java:103) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor350.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:511) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-445]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-445]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by EpiCanard** [comment]
Hello,

In last release we changed the behavior of import command.
The root folder has been changed to `plugins/ServerSigns` and all your file to import must be here or in a sub folder.
Your file to import must be a .txt too.

**Comment by Dude42069Nice** [comment]
all my files to import are in plugins/ServerSigns and all of my files are .txt
when i try to rightclick on sign after using import command i only get "An error has occurred please refer to console for details"
i use this command like this /svs import wiadro.txt 
i really need it to work becouse i have really long set of commands which distribute players to prebuild houses and now any file that i try to import returns an error

**Comment by EpiCanard** [comment]
Can you send me your file your are trying to import ?

**Comment by Dude42069Nice** [comment]
i can but this problem appears with every file that i try to import
[wiadro.txt](https://github.com/serversigns/ServerSigns/files/6009329/wiadro.txt)

**Comment by EpiCanard** [comment]
I confirm the bug on my side
